"""add shops

Revision ID: 5cc608ea1952
Revises: 61552013e222
Create Date: 2025-07-08 18:27:30.965946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cc608ea1952'
down_revision: Union[str, None] = '61552013e222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopitems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rewardusers')
    op.add_column('events', sa.Column('reward', sa.Integer(), nullable=False))
    op.drop_column('events', 'reward_id')
    op.drop_constraint(op.f('eventusers_event_id_fkey'), 'eventusers', type_='foreignkey')
    op.create_foreign_key(None, 'eventusers', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eventusers', type_='foreignkey')
    op.create_foreign_key(op.f('eventusers_event_id_fkey'), 'eventusers', 'events', ['event_id'], ['id'])
    op.add_column('events', sa.Column('reward_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('events', 'reward')
    op.create_table('rewardusers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reward_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('rewardusers_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rewardusers_pkey'))
    )
    op.drop_table('shopitems')
    # ### end Alembic commands ###
