"""change event model

Revision ID: 61552013e222
Revises: b1af621d9750
Create Date: 2025-07-04 16:43:50.585188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61552013e222'
down_revision: Union[str, None] = 'b1af621d9750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date_and_time', sa.DateTime(), nullable=False))
    op.drop_column('events', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('events', 'date_and_time')
    # ### end Alembic commands ###
