"""change eventuser

Revision ID: 6e7d89190c5f
Revises: 5cc608ea1952
Create Date: 2025-09-08 19:29:43.431098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7d89190c5f'
down_revision: Union[str, None] = '5cc608ea1952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventusers', 'attended',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventusers', 'attended',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
