"""add fields into User

Revision ID: a71121dd8f9b
Revises: b95306701af4
Create Date: 2026-01-29 09:31:31.503994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71121dd8f9b'
down_revision: Union[str, None] = 'b95306701af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('church', sa.String(), nullable=True))
    op.add_column('users', sa.Column('referral_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_source')
    op.drop_column('users', 'church')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
