"""change event model

Revision ID: b1af621d9750
Revises: 203a8e27adcf
Create Date: 2025-07-04 16:15:13.270040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1af621d9750'
down_revision: Union[str, None] = '203a8e27adcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.drop_column('events', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('events', 'datetime')
    # ### end Alembic commands ###
