"""delete photo url and add bucket_name, file_path

Revision ID: b77566d78904
Revises: 0a1d32e02665
Create Date: 2025-09-19 20:15:32.357329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77566d78904'
down_revision: Union[str, None] = '0a1d32e02665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('bucket_name', sa.String(), nullable=True))
    op.add_column('events', sa.Column('file_path', sa.String(), nullable=True))
    op.drop_column('events', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('events', 'file_path')
    op.drop_column('events', 'bucket_name')
    # ### end Alembic commands ###
