"""change fields shopitem

Revision ID: f2a902461597
Revises: a71121dd8f9b
Create Date: 2026-03-04 17:49:20.848415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2a902461597'
down_revision: Union[str, None] = 'a71121dd8f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rewards')
    op.drop_table('rewarditems')
    op.add_column('shopitems', sa.Column('bucket_name', sa.String(), nullable=True))
    op.add_column('shopitems', sa.Column('file_path', sa.String(), nullable=True))
    op.drop_column('shopitems', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopitems', sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('shopitems', 'file_path')
    op.drop_column('shopitems', 'bucket_name')
    op.create_table('rewarditems',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('rewarditems_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='rewarditems_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('rewards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('COINS', name='rewardtypeenum'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['rewarditems.id'], name=op.f('rewards_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rewards_pkey'))
    )
    # ### end Alembic commands ###
